# docker/docker-compose.yml
version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8443:8443"   # HTTPS local mapeado para host 8443
      - "8080:8080"   # optional redirect server
    volumes:
      - ../certs/server:/etc/nginx/certs/server:ro
      - ../nginx_site/html:/usr/share/nginx/html:ro
    restart: unless-stopped
